DELETE http://localhost:3003/api/blogs/653e6b31c8abdb6f767c3a11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvdGFybyIsImlkIjoiNjUzZTU5ODAxYWQ3N2U2ZWU0ZDFmZDZkIiwiaWF0IjoxNjk4NTg2MDMwfQ.yIEvCg2kde-MyMSXz5UqXv89P8nByy1DVXKUuflHbTY
